from datetime import datetime
from helpers import _HTTP_MAP, _HELIOS_FDR_KEY, _HELIOS_START_DATE_KEY
from helpers import _HELIOS_END_DATE_KEY, _HELIOS_STATEMENT_TYPE_KEY

_APPIAN_FDR_ID_LIST_KEY = "FDR_IDS_LIST"
_APPIAN_START_DATE_KEY = "START_DATE"
_APPIAN_END_DATE_KEY = "END_DATE"
_APPIAN_NICKNAME_LIST_KEY = "NICKNAME_ID_LIST"
_APPIAN_AGENT_LIST_KEY = "AGENT_ID_LIST"
_APPIAN_STATEMENT_TYPE_KEY = "STATEMENT_TYPE"
_APPIAN_TEMPLATE_NAME_KEY = "TEMPLATE_NAME"


class AppianFDRConfig:

    def __init__(self):

        self._http_arg_map = [
            _HTTP_MAP(_HELIOS_FDR_KEY, _APPIAN_FDR_ID_LIST_KEY, True)
        ]